name: Build and Push Redfish-Exporter Docker Image

on:
  push:
    tags:
      - "v*" # Trigger only when a tag starting with 'v' is pushed

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version from tag
        id: get_version
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,' | sed -e 's/^v//')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push amd64
        run: |
          docker buildx build --platform linux/amd64 --build-arg TARGETARCH=amd64 \
            -t ghcr.io/asama-ai/redfish-exporter:${{ steps.get_version.outputs.version }}-amd64 --push .

      - name: Build and push arm64
        run: |
          docker buildx build --platform linux/arm64 --build-arg TARGETARCH=arm64 \
            -t ghcr.io/asama-ai/redfish-exporter:${{ steps.get_version.outputs.version }}-arm64 --push .

      - name: Create multi-arch image (single tag)
        run: |
          docker buildx imagetools create \
            -t ghcr.io/asama-ai/redfish-exporter:${{ steps.get_version.outputs.version }} \
            -t ghcr.io/asama-ai/redfish-exporter:latest \
            ghcr.io/asama-ai/redfish-exporter:${{ steps.get_version.outputs.version }}-amd64 \
            ghcr.io/asama-ai/redfish-exporter:${{ steps.get_version.outputs.version }}-arm64
