name: Build and Push Redfish-Exporter Docker Image

on:
  push:
    tags:
      - "v*" # Trigger only when a tag starting with 'v' is pushed

jobs:
  build:
    runs-on: ubuntu-24.04 # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the code
      - name: Checkout redfish-exporter Code
        uses: actions/checkout@v4

      # Step 2: Set up Go (or your build environment)
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.2" # Specify the Go version

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version from tag
        id: get_version
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,' | sed -e 's/^v//')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # Step 3: Set up Docker Buildx (for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 4: Build and push Docker image for amd64 and arm64
      - name: Build and push Docker image (amd64 + arm64)
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/asama-ai/redfish-exporter:${{ steps.get_version.outputs.version }}
            ghcr.io/asama-ai/redfish-exporter:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
